/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaApp.View;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.ResultSet; // Import this
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;




/**
 *
 * @author artii
 */
public class UpdateTicket extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public UpdateTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DashHome = new javax.swing.JLabel();
        BookTicket = new javax.swing.JLabel();
        DashBookingDetails = new javax.swing.JLabel();
        DashUpdateTicket = new javax.swing.JLabel();
        DashCancelTicket = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fromComboBox = new javax.swing.JComboBox<>();
        destinationComboBox = new javax.swing.JComboBox<>();
        flightComboBox = new javax.swing.JComboBox<>();
        departureTimeComboBox = new javax.swing.JComboBox<>();
        ticketNoTextField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        passengerNoTextField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        contactNoField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        arrivaltimeComboBox = new javax.swing.JComboBox<>();
        seatField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(349, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/brand.png"))); // NOI18N

        DashHome.setBackground(new java.awt.Color(244, 240, 235));
        DashHome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DashHome.setForeground(new java.awt.Color(219, 212, 199));
        DashHome.setIcon(new FlatSVGIcon("home.svg"));
        DashHome.setText("   Home");
        DashHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashHomeMouseClicked(evt);
            }
        });

        BookTicket.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BookTicket.setForeground(new java.awt.Color(220, 213, 199));
        BookTicket.setIcon(new FlatSVGIcon("ticket.svg"));
        BookTicket.setText("   Book Ticket");
        BookTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookTicketMouseClicked(evt);
            }
        });

        DashBookingDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DashBookingDetails.setForeground(new java.awt.Color(219, 212, 199));
        DashBookingDetails.setIcon(new FlatSVGIcon("details.svg"));
        DashBookingDetails.setText("   Booking Details");
        DashBookingDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashBookingDetailsMouseClicked(evt);
            }
        });

        DashUpdateTicket.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DashUpdateTicket.setForeground(new java.awt.Color(219, 212, 199));
        DashUpdateTicket.setIcon(new FlatSVGIcon("update.svg"));
        DashUpdateTicket.setText("   Update Ticket");
        DashUpdateTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashUpdateTicketMouseClicked(evt);
            }
        });

        DashCancelTicket.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DashCancelTicket.setForeground(new java.awt.Color(219, 212, 199));
        DashCancelTicket.setIcon(new FlatSVGIcon("cancel.svg"));
        DashCancelTicket.setText("   Cancel Ticket");
        DashCancelTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashCancelTicketMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DashHome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DashBookingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(DashCancelTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DashUpdateTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(DashHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(BookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(DashBookingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(DashUpdateTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(DashCancelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 1080));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setName(""); // NOI18N
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1620, 70));

        jPanel3.setBackground(new java.awt.Color(246, 241, 234));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1600, 1080));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Update Ticket");

        fromComboBox.setBackground(new java.awt.Color(248, 242, 242));
        fromComboBox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        fromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", " " }));
        fromComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        fromComboBox.setPreferredSize(new java.awt.Dimension(145, 35));
        fromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromComboBoxActionPerformed(evt);
            }
        });

        destinationComboBox.setBackground(new java.awt.Color(248, 242, 242));
        destinationComboBox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        destinationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mustang", "Pokhara", "Chitwan", "Kathmandu" }));
        destinationComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        destinationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationComboBoxActionPerformed(evt);
            }
        });

        flightComboBox.setBackground(new java.awt.Color(248, 242, 242));
        flightComboBox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        flightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flight E3", "Flight 204", "Flight B23", "Flight E2D", " " }));
        flightComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        flightComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightComboBoxActionPerformed(evt);
            }
        });

        departureTimeComboBox.setBackground(new java.awt.Color(248, 242, 242));
        departureTimeComboBox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        departureTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "02:00 PM", "04:00 PM", "11:00 AM", "07:00 AM" }));
        departureTimeComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        ticketNoTextField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ticketNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketNoTextFieldActionPerformed(evt);
            }
        });

        dateField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });

        passengerNoTextField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        customerNameField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        customerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameFieldActionPerformed(evt);
            }
        });

        contactNoField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        addressField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        arrivaltimeComboBox.setBackground(new java.awt.Color(248, 242, 242));
        arrivaltimeComboBox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        arrivaltimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "03:00 PM", "05:00 PM", "12:00 AM", "08:00 AM", " " }));

        seatField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        seatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatFieldActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(171, 112, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setIcon(new FlatSVGIcon("Tick3.svg"));
        jButton2.setText("    Update Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Ticket No:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Flight Name");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setText("Date:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("From:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setText("Destination:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setText("No. Of Passenger:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Depature Time");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setText("Arrival Time:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setText("Customer Name:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Contact No:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setText("Address:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("Seat:");

        jButton1.setBackground(new java.awt.Color(171, 112, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addComponent(jLabel21)
                    .addComponent(jLabel8))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(flightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureTimeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passengerNoTextField)
                    .addComponent(destinationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromComboBox, 0, 232, Short.MAX_VALUE)
                    .addComponent(arrivaltimeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 229, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactNoField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)
                                .addGap(76, 76, 76)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel13)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(18, 18, 18)
                                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(141, 141, 141)
                                        .addComponent(seatField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ticketNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel16)
                                    .addComponent(jButton1))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(contactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(seatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(destinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addComponent(passengerNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(49, 49, 49)))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departureTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(40, 40, 40)
                        .addComponent(arrivaltimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(314, 314, 314))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 1220, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void destinationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationComboBoxActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void customerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameFieldActionPerformed

    private void seatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    String ticketNo = ticketNoTextField.getText();
    String flightId = (String) flightComboBox.getSelectedItem();
    String departureFrom = (String) fromComboBox.getSelectedItem();
    String destination = (String) destinationComboBox.getSelectedItem();
    String date = dateField.getText();
    String noOfPassenger = passengerNoTextField.getText();
    String departureTime = (String) departureTimeComboBox.getSelectedItem();
    String arrivalTime = (String) arrivaltimeComboBox.getSelectedItem();
    String seat = seatField.getText();
    String customerName = customerNameField.getText();
    String contactNo = contactNoField.getText();
    String address = addressField.getText();

    SimpleDateFormat inputFormat = new SimpleDateFormat("hh:mm a");
    SimpleDateFormat outputFormat = new SimpleDateFormat("HH:mm:ss");
    String departureTimeFormatted = "";
    String arrivalTimeFormatted = "";

    try {
        if (departureTime != null && !departureTime.trim().isEmpty()) {
            java.util.Date dateObj = inputFormat.parse(departureTime);
            departureTimeFormatted = outputFormat.format(dateObj);
        }
        if (arrivalTime != null && !arrivalTime.trim().isEmpty()) {
            java.util.Date dateObj = inputFormat.parse(arrivalTime);
            arrivalTimeFormatted = outputFormat.format(dateObj);
        }
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Invalid time format. Please use hh:mm a.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (ticketNo.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a ticket number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Connection conn = null;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines", "root", "admin123");
        String sql = "UPDATE Tickets SET flight_id = ?, departure_from = ?, destination = ?, date = ?, no_of_passenger = ?, departure_time = ?, arrival_time = ?, seat = ?, customer_name = ?, contact_no = ?, address = ? WHERE ticket_no = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, flightId);
        ps.setString(2, departureFrom);
        ps.setString(3, destination);
        ps.setString(4, date);
        ps.setString(5, noOfPassenger);
        ps.setString(6, departureTimeFormatted);
        ps.setString(7, arrivalTimeFormatted);
        ps.setString(8, seat);
        ps.setString(9, customerName);
        ps.setString(10, contactNo);
        ps.setString(11, address);
        ps.setString(12, ticketNo);
        int rowsUpdated = ps.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Ticket details updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            // Refresh the table data
            refreshTable();
        } else {
            JOptionPane.showMessageDialog(this, "Ticket number not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        ps.close();
    } catch (ClassNotFoundException | SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error updating data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

// Method to refresh the table data
private void refreshTable() {
    Connection conn = null;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines", "root", "admin123");
        String sql = "SELECT * FROM Tickets";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();
        model.setRowCount(0);
        while (rs.next()) {
            model.addRow(new Object[] {
                rs.getString("ticket_no"),
                rs.getString("flight_id"),
                rs.getString("departure_from"),
                rs.getString("destination"),
                rs.getString("date"),
                rs.getString("no_of_passenger"),
                rs.getString("departure_time"),
                rs.getString("arrival_time"),
                rs.getString("seat"),
                rs.getString("customer_name"),
                rs.getString("contact_no"),
                rs.getString("address")
            });
        }
        rs.close();
        ps.close();
    } catch (ClassNotFoundException | SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error retrieving data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
    private void flightComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightComboBoxActionPerformed

    private void fromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromComboBoxActionPerformed

    private void ticketNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketNoTextFieldActionPerformed

    private void DashHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashHomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        HomePage hp= new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_DashHomeMouseClicked

    private void BookTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTicketMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ticketbook tb= new ticketbook();
        tb.setVisible(true);
        
    }//GEN-LAST:event_BookTicketMouseClicked

    private void DashBookingDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBookingDetailsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Bookdetails bd= new Bookdetails();
        bd.setVisible(true);
    }//GEN-LAST:event_DashBookingDetailsMouseClicked

    private void DashUpdateTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashUpdateTicketMouseClicked
        // TODO add your handling code here:
        this.dispose();
        UpdateTicket ut= new UpdateTicket();
        ut.setVisible(true);
        
    }//GEN-LAST:event_DashUpdateTicketMouseClicked

    private void DashCancelTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashCancelTicketMouseClicked
        // TODO add your handling code here:
        this.dispose();
        CancelTicket ct= new CancelTicket();
        ct.setVisible(true);
    }//GEN-LAST:event_DashCancelTicketMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ticketNo = ticketNoTextField.getText();
        if (ticketNo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a ticket number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Connection conn = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines", "root", "admin123");
            String sql = "SELECT * FROM Tickets WHERE ticket_no = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, ticketNo);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                flightComboBox.setSelectedItem(rs.getString("flight_id"));
                fromComboBox.setSelectedItem(rs.getString("departure_from"));
                destinationComboBox.setSelectedItem(rs.getString("destination"));
                dateField.setText(rs.getString("date"));
                passengerNoTextField.setText(rs.getString("no_of_passenger"));
                departureTimeComboBox.setSelectedItem(rs.getString("departure_time"));
                arrivaltimeComboBox.setSelectedItem(rs.getString("arrival_time"));
                seatField.setText(rs.getString("seat"));
                customerNameField.setText(rs.getString("customer_name"));
                contactNoField.setText(rs.getString("contact_no"));
                addressField.setText(rs.getString("address"));
            } else {
                JOptionPane.showMessageDialog(this, "Invalid ticket number.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            rs.close();
            ps.close();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookTicket;
    private javax.swing.JLabel DashBookingDetails;
    private javax.swing.JLabel DashCancelTicket;
    private javax.swing.JLabel DashHome;
    private javax.swing.JLabel DashUpdateTicket;
    private javax.swing.JTextField addressField;
    private javax.swing.JComboBox<String> arrivaltimeComboBox;
    private javax.swing.JTextField contactNoField;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JTextField dateField;
    private javax.swing.JComboBox<String> departureTimeComboBox;
    private javax.swing.JComboBox<String> destinationComboBox;
    private javax.swing.JComboBox<String> flightComboBox;
    private javax.swing.JComboBox<String> fromComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField passengerNoTextField;
    private javax.swing.JTextField seatField;
    private javax.swing.JTextField ticketNoTextField;
    // End of variables declaration//GEN-END:variables
}
